//This file is generated by tools!
//Please do not modify this file!
public class DataDefine {

	public const int Achievement_Achievement_achId = 0;
	public const int Achievement_Achievement_title = 1;
	public const int Achievement_Achievement_desc = 2;
	public const int Achievement_Achievement_icon = 3;
	public const int Achievement_Achievement_cond1_type = 4;
	public const int Achievement_Achievement_cond1_value = 5;
	public const int Achievement_Achievement_cond1_bonus = 6;
	public const int Achievement_Achievement_cond2_type = 7;
	public const int Achievement_Achievement_cond2_value = 8;
	public const int Achievement_Achievement_cond2_bonus = 9;
	public const int Achievement_Achievement_cond3_type = 10;
	public const int Achievement_Achievement_cond3_value = 11;
	public const int Achievement_Achievement_cond3_bonus = 12;
	public const int Achievement_Achievement_all_finishd_bonus = 13;
	public const int Achievement_Achievement_productId = 14;
	public const int Achievement_Achievement2_achId = 0;
	public const int Achievement_Achievement2_title = 1;
	public const int Achievement_Achievement2_desc = 2;
	public const int Achievement_Achievement2_icon = 3;
	public const int Achievement_Achievement2_cond1_type = 4;
	public const int Achievement_Achievement2_cond1_value = 5;
	public const int Achievement_Achievement2_cond1_bonus = 6;
	public const int Achievement_Achievement2_cond2_type = 7;
	public const int Achievement_Achievement2_cond2_value = 8;
	public const int Achievement_Achievement2_cond2_bonus = 9;
	public const int Achievement_Achievement2_cond3_type = 10;
	public const int Achievement_Achievement2_cond3_value = 11;
	public const int Achievement_Achievement2_cond3_bonus = 12;
	public const int Achievement_Achievement2_all_finishd_bonus = 13;
	public const int Achievement_Achievement2_productId = 14;

}